/**
 * Frontend mirror of the edge-side decision-context MODEL_VERSION.
 *
 * Source of truth: supabase/functions/_shared/decision-context/constants.ts
 * Keep these two in sync when bumping the builder version. When a fetched
 * decision_context row has a stale `model_version`, the UI auto-rebuilds it
 * once (see useDecisionContext) so users never see panels generated by a
 * deprecated pipeline.
 */
export const CURRENT_DECISION_CONTEXT_MODEL_VERSION = "decision-context-v1.1.0";
