// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createScreenshotMockClient } from './mockClient';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SCREENSHOT_MODE = import.meta.env.VITE_SCREENSHOT_MODE === '1';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = SCREENSHOT_MODE
  ? createScreenshotMockClient()
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });